# TextDraw Anti-Aliasing Fix v1.0.0
# Created by sonochiwa
# Source code: https://github.com/sonochiwa/sa-textdraw-anti-aliasing-fix
# Default toggle hotkey: Alt + T

[general]
isEnabled=1
hotkeyEnabled=1
hotkeyModifier=18
hotkeyKey=84
logging=0
dumpPreviews=0

[antiAliasing]
supersample=4
previewScale=2
